/**
 * A real OpenSSH server for the end-to-end tests.
 *
 * Mocking an SSH server proves very little: the interesting failures are in
 * the handshake, in host key handling and in what sshd does with the file
 * permissions of authorized_keys. So the tests run against sshd itself when
 * the machine has one, and skip when it does not (Windows, and CI images
 * without openssh-server).
 *
 * The host key is generated by this package rather than by ssh-keygen, which
 * incidentally proves the generated format is one OpenSSH accepts.
 */

import { execFileSync, spawn, type ChildProcess } from "node:child_process";
import * as fs from "node:fs";
import * as net from "node:net";
import * as os from "node:os";
import * as path from "node:path";
import { generateKeyPair } from "../src/keys.ts";

const SSHD_CANDIDATES = ["/usr/sbin/sshd", "/usr/local/sbin/sshd", "/sbin/sshd"];

export function findSshd(): string | null {
  if (process.platform === "win32") return null;
  for (const candidate of SSHD_CANDIDATES) {
    if (fs.existsSync(candidate)) return candidate;
  }
  return null;
}

function findSftpServer(): string | null {
  for (const candidate of [
    "/usr/lib/openssh/sftp-server",
    "/usr/libexec/openssh/sftp-server",
    "/usr/libexec/sftp-server",
    "/usr/lib/ssh/sftp-server",
  ]) {
    if (fs.existsSync(candidate)) return candidate;
  }
  return null;
}

async function freePort(): Promise<number> {
  return new Promise((resolve, reject) => {
    const server = net.createServer();
    server.once("error", reject);
    server.listen(0, "127.0.0.1", () => {
      const port = (server.address() as net.AddressInfo).port;
      server.close(() => resolve(port));
    });
  });
}

async function waitForPort(port: number, timeoutMs = 10_000): Promise<boolean> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const open = await new Promise<boolean>((resolve) => {
      const socket = net.connect(port, "127.0.0.1");
      socket.once("connect", () => {
        socket.destroy();
        resolve(true);
      });
      socket.once("error", () => {
        socket.destroy();
        resolve(false);
      });
    });
    if (open) return true;
    await new Promise((resolve) => setTimeout(resolve, 100));
  }
  return false;
}

export interface TestServer {
  readonly port: number;
  readonly user: string;
  readonly dir: string;
  /** Home directory sshd resolves ~ to, and where authorized_keys lives. */
  readonly home: string;
  readonly clientKeyPath: string;
  readonly authorizedKeysPath: string;
  stop(): void;
}

/**
 * Start sshd on a free loopback port, authorising one generated client key.
 * Returns null when this machine has no sshd to run.
 */
export async function startTestServer(): Promise<TestServer | null> {
  const sshd = findSshd();
  const sftp = findSftpServer();
  if (!sshd) return null;

  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "pi-ssh-sshd-"));
  const home = path.join(dir, "home");
  const sshDir = path.join(home, ".ssh");
  fs.mkdirSync(sshDir, { recursive: true, mode: 0o700 });

  const hostKey = generateKeyPair("test host");
  const hostKeyPath = path.join(dir, "host_ed25519");
  fs.writeFileSync(hostKeyPath, hostKey.privateKey, { mode: 0o600 });
  fs.chmodSync(hostKeyPath, 0o600);

  const clientKey = generateKeyPair("test client");
  const clientKeyPath = path.join(dir, "client_ed25519");
  fs.writeFileSync(clientKeyPath, clientKey.privateKey, { mode: 0o600 });
  fs.chmodSync(clientKeyPath, 0o600);

  const authorizedKeysPath = path.join(sshDir, "authorized_keys");
  fs.writeFileSync(authorizedKeysPath, `${clientKey.publicKey}\n`, { mode: 0o600 });

  const port = await freePort();
  const configPath = path.join(dir, "sshd_config");
  fs.writeFileSync(
    configPath,
    [
      `Port ${port}`,
      "ListenAddress 127.0.0.1",
      `HostKey ${hostKeyPath}`,
      `PidFile ${path.join(dir, "sshd.pid")}`,
      `AuthorizedKeysFile ${authorizedKeysPath}`,
      "StrictModes no",
      "UsePAM no",
      "PasswordAuthentication no",
      "PubkeyAuthentication yes",
      ...(sftp ? [`Subsystem sftp ${sftp}`] : []),
    ].join("\n") + "\n",
  );

  let child: ChildProcess | null = null;
  try {
    // -D keeps it in the foreground so the child handle can stop it again.
    child = spawn(sshd, ["-D", "-f", configPath, "-e"], { stdio: "ignore" });
  } catch {
    fs.rmSync(dir, { recursive: true, force: true });
    return null;
  }

  if (!(await waitForPort(port))) {
    child.kill("SIGKILL");
    fs.rmSync(dir, { recursive: true, force: true });
    return null;
  }

  return {
    port,
    user: os.userInfo().username,
    dir,
    home,
    clientKeyPath,
    authorizedKeysPath,
    stop() {
      try {
        child?.kill("SIGKILL");
      } catch {
        /* already gone */
      }
      fs.rmSync(dir, { recursive: true, force: true });
    },
  };
}

/** True when this machine can run the end-to-end tests at all. */
export function sshdAvailable(): boolean {
  if (!findSshd()) return false;
  try {
    execFileSync(findSshd()!, ["-t", "-f", "/dev/null"], { stdio: "ignore" });
    return true;
  } catch {
    // -t on an empty config still exits non-zero on some builds; the real
    // check is whether startTestServer manages to listen.
    return true;
  }
}
